LANGS = {
    "hi": "Hindi",
    "en": "English",
    "fr": "French",
    "de": "German",
    "es": "Spanish",
    "ru": "Russian",
    "zh": "Chinese",
    "ar": "Arabic",
    "tr": "Turkish",
    "vi": "Vietnamese",
    "th": "Thai",
    "ur": "Urdu",
    "sw": "Swahili",
    "bg": "Bulgarian",
    "el": "Greek",
    "qu": "Quechua",
    "sw": "Swahili",
    "it": "Italian",
    "ja": "Japanese",
    "ko": "Korean",
    "pt": "Portuguese",
    "ro": "Romanian",
    "pl": "Polish",
    "cs": "Czech",
    "et": "Estonian",
    "da": "Danish",
    "id": "Indonesian",
    "ht": "Haitian Creole",
    "ta": "Tamil",
}
