save_dir: 'contamination/quizzes'
dataset_name: xnli
model_name: palm-32k
max_tokens: 5000
temperature: 1.0
template_name: xnli
dataset_split: test # default is test, if test is not available use validation else use train
chat_prompt: False
substrate_prompt: False
langs: ['en']