key_path: /home/t-daggarwal/MultilingualBlanketEval/keys/openai_key.txt
k: 4
model: mistralai/Mistral-7B-Instruct-v0.2
chat_prompt: False
turbo_identifier: mistralai/Mistral-7B-Instruct-v0.2
instruction_identifier: xlsum
response_logger_root: /home/t-daggarwal/MultilingualBlanketEval/results/XLSum/mistral_2/
prompt_selection: False
sleep_period: 60
wandb_log: False
langs:
  - "swahili"
  - "tamil"
  - "thai"
  - "russian"
  - "portuguese"
  - "arabic"
  - "hindi"
  - "igbo"
  - "indonesian"
  - "urdu"
  - "kyrgyz"
  - "oromo"
  - "amharic"
  - "azerbaijani"
  - "burmese"
  - "chinese_simplified"
  - "welsh"
  - "kirundi"
  - "hausa"
  - "scottish_gaelic"
  - "nepali"
  - "pashto"
  - "persian"
  - "pidgin"
  - "serbian_cyrillic"
  - "serbian_latin"
  - "sinhala"
  - "somali"
  - "tigrinya"
  - "turkish"
  - "ukrainian"
  - "uzbek"
  - "vietnamese"
  - "yoruba"
dataset_frac: 1
random_seed: 42
max_prompt_selection_samples: 1000
max_new_tokens: 400
temperature: 0
substrate_prompt: False
metric_logger_path: "xlsum_mistral_2_instruct_metrics.csv"
prompt_names:
  - DOC_write_summary_of_above
# For xlsum language codes check https://huggingface.co/datasets/csebuetnlp/xlsum/blob/main/xlsum.py or the dataloader for xlsum
