description: MEGAVERSE

target:
  service: sing
  name: msrresrchvc
  workspace_name: msrresrchws
  resource_group: gcr-singularity-resrch

environment:
  image: amlt-sing/acpt-2.1.2-cuda11.8
  # image_setup: 
  # - conda install conda=23.10.0 -y
  # - conda env create --name megaverse --file=mega_env.yml

  setup:
  - conda install conda=23.10.0 -y
  # - conda env create --name megaverse --file=mega_env.yml -y
  # - conda activate megaverse
  - python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 --force
  - python -c "import torch; print('GPU Support:',torch.cuda.is_available())"
  - which pip
  - conda install cudatoolkit==12.1 -y
  - which python
  - python -m pip install chardet
  - python -m pip install transformers
  - python -m pip install accelerate
  - python -m pip install deepspeed
  - python -m pip install openai
  - python -m pip install google-generativeai
  - python -m pip install flash_attn==2.5.5
  - python -m pip install git+https://github.com/lm-sys/FastChat.git
  - python -m pip install python-dotenv
  - pip install -e promptsource/

  
code: 
  local_dir: $CONFIG_DIR/..
  ignore:
  - data/*
  - MEGANotebooks/*

storage:
  megaverse:
    storage_account_name: multillmft
    container_name: megaverse
    mount_dir: /mnt/megaverse


jobs:
  - name: megaverse_xnli_gemma
    sku: 80G1-A100
    priority: High
    sla_tier: Standard
    command:
      - nvidia-smi
      - conda activate megaverse
      - bash hf_scripts/run_xnli_all.sh