description: MEGAVERSE_XLSUM_GEMMA

target:
  service: sing
  name: msrresrchvc
  workspace_name: msrresrchws
  resource_group: gcr-singularity-resrch

environment:
  image: amlt-sing/acpt-2.1.2-cuda11.8
  image_setup: 
  - conda install conda=23.10.0 -y
  # - conda env create --name megaverse --file=mega_env.yml

  setup:
  # - conda install conda=23.10.0 -y
  # - conda update -n base -c defaults conda
  # - conda env create --name megaverse --file=mega_env.yml
  # - conda activate megaverse
  - python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 --force
  - python -c "import torch; print('GPU Support:',torch.cuda.is_available())"
  - which pip
  - conda install cudatoolkit==12.1 -y
  - which python
  - python -m pip install chardet
  - python -m pip install transformers -U
  - python -m pip install accelerate
  - python -m pip install deepspeed
  - python -m pip install datasets
  - python -m pip install sentencepiece
  - python -m pip install backoff
  - python -m pip install openai==0.28.0
  - python -m pip install google-generativeai
  - python -m pip install flash_attn==2.5.5
  - python -m pip install wandb
  - python -m pip install rouge_score
  - python -m pip install git+https://github.com/lm-sys/FastChat.git
  - python -m pip install python-dotenv
  - python -m pip install azure-ai-translation-text==1.0.0b1
  - python -m pip install langchain
  - python -m pip install --upgrade evaluate
  - python -m pip install --upgrade huggingface_hub
  - python -m pip install -r requirements_gemma.txt
  - python -m pip install -e promptsource/

  
code: 
  local_dir: $CONFIG_DIR/..
  ignore:
  - data/*
  - MEGANotebooks/*
  - xrisawoz_data/*
  - results/*

storage:
  megaverse:
    storage_account_name: multillmft
    container_name: megaverse
    mount_dir: /mnt/megaverse


jobs:
  - name: megaverse_xlsum_gemma
    sku: 80G1-A100
    priority: High
    sla_tier: Standard
    command:
      - nvidia-smi
      # - conda activate megaverse
      - ls
      - python -m pip install langchain --user
      - python -m pip install -e promptsource/ --user
      - python -m pip install transformers -U --user
      - huggingface-cli login --token "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"
      - bash hf_scripts/run_xlsum.sh "/mnt/megaverse/results"